src/Modules/activities.ts, src/Modules/boops.ts, src/Modules/collar.ts, src/Modules/hypno.ts, src/Modules/lipstick.ts, src/Modules/misc.ts, src/Settings/boops.ts, src/Settings/collar.ts, src/Settings/global.ts, src/Settings/hypno.ts, src/Settings/lipstick.ts, src/Settings/mainmenu.ts, src/Settings/misc.ts, src/Settings/settingBase.ts, src/Settings/settingUtils.ts, src/Settings/setting_definitions.ts, src/base.ts, src/main.ts, src/modules.ts
This removes the hardcoded settings arrays in favor of each module registering its own screen (name, icon and title), and refactors the code so screen discovery and unloading is more streamlined (I needed the latter for `Unload()` to work correctly, but then ended up not needing it 🤷).
Then the registration of default settings is moved over to modules themselves instead of subscreens, removing all the duplication, and make the screens go through their respective module when accessing settings. Most of the getters are now just a passthrough from a screen to the abstract class, to its module, to the abstract class.
This fixes a crash where opening the General settings would crash, as it would only initialize its values but tried to access stuff in the Misc module.
=> Refactor module load and settings registration

src/Modules/core.ts, src/utils.ts
- Bump overlay position to try and prevent bleed in full rooms
- Trim 'v' on bcMod api register to look right in /versions listing
=> Version overlay fix

src/Modules/injector.ts, src/Modules/misc.ts, src/Settings/Models/injector.ts, src/base.ts, src/utils.ts
Latex Respirator enhancements to allow continuous LSCG drug delivery
- Requires a crafted Latex Respirator with LSCG drug keyword(s)
- Respirator must have small or large tubes and they must have glow on to be "activated"
- Drug levels will slowly grow over time, with random events resulting in emotes, jumps in drug level, incapacitation minigames, and forced orgasms
- Once a respirator is "activated" (by wearing + turning the glow on) it will last an hour until it runs out of "gas"
- Repirators can be reloaded by turning the 'glow' back on.
- Supports BCX cursing the respirator settings which can result in auto-reloading.
=> Continuous drug delivery via Respirator

src/Modules/activities.ts, src/Modules/hypno.ts, src/Modules/injector.ts, src/Settings/Models/activities.ts, src/Settings/Models/base.ts, src/Settings/Models/injector.ts, src/Settings/Models/settings.ts, src/Settings/activities.ts, src/Settings/injector.ts, src/main.ts, src/utils.ts
Allows the user to configure specific activities on specific locations.
These activities can:
* Act as a hypnotic trigger, with configurable values for: 
* How many times within 5 minutes the activity must be performed
* What the user's arousal must be at for this activity + zone to induce a trance
* Act as an awakener for hypnosis and drugged sleep
* This replaces the previous "allow boop awake" and adds 'boop nose' as an awakener by default
* Cause an orgasm if the user's arousal is above a certain threshold
=> Implement activities configuration menu and effects.

src/Modules/activities.ts, src/Modules/item-use.ts, src/Settings/activities.ts
* Moving items around will be back to using the source asset's name (eg, scarf vs bandana)
=> Adjust for beta change around UsedAsset vs ActivityAsset

lscgLoader-dev.user.js, lscgLoader.user.js, package.json, rollup.config.mjs, src/Modules/States/ItemBundleBaseState.ts, src/Modules/States/PolymorphedState.ts, src/Modules/States/RedressedState.ts, src/Modules/activities.ts, src/Modules/core.ts, src/Modules/item-use.ts, src/Modules/magic.ts, src/Settings/Models/magic.ts, src/Settings/magic.ts, src/club_existing/declarations.d.ts, src/club_existing/mbs.d.ts, src/main.ts, src/utils.ts
* Allow using MBS and Wardrobe sets for outfit/polymorph spell effects.
* Use index number for Wardrobe and set name for MBS sets
* This allows for data reuse and should help reduce packet size for LSCG users
* Trim base64 outfit/polymorph codes on save.
* When you save an encoded ItemBundle[] list, it will be filtered for items that actually apply to the spell effect, throwing away unnecessary data.
* Switch tampermonkey loader to use 'script' type instead of 'module' to better export a public API.
* TAMPERMONKEY LOADER NEEDS REINSTALL FOR THIS TO WORK
* Move bread eat activity to mouth to match sip + quaff
=> Dev refactors and improvements

src/Settings/settingUtils.ts
Changed `drawTooltip` to use BC functions, instead of canvas specific ones.
=> Changes to `drawTooltip`

lscgLoader-dev.user.js, lscgLoader.user.js, package.json, src/Modules/States/FrozenState.ts, src/Modules/States/ItemBundleBaseState.ts, src/Modules/States/PolymorphedState.ts, src/Modules/States/RedressedState.ts, src/Modules/States/XRayVisionState.ts, src/Modules/activities.ts, src/Modules/core.ts, src/Modules/item-use.ts, src/Modules/magic.ts, src/Modules/states.ts, src/Settings/Models/magic.ts, src/Settings/Models/settings.ts, src/Settings/Remote/magic.ts, src/Settings/magic.ts, src/club_existing/bc/Typedef.d.ts, src/club_existing/type-overrides.d.ts
* Null check fix for rope tie activity
* Fix for error during DrawImageResize on activity thumbnails
* Fix "Petrified" spell effect not preventing movement in new map rooms
* Allow opacity on any clothing item
* Note: Only visible when using LSCG. Clipping issues very possible.
* Add "X-ray vision" spell effect
* Will render all clothes at 50% opacity if the wearer has magic enabled and has not set "Prevent X-Ray" true in their magic settings.
=> Updates and Fixes from Dev

src/Modules/injector.ts
Fixes an invalid group name: `Handheld` -> `ItemHandheld`.
=> BUG: Fix `HoldingDruggedDrink` checking for items in the wrong group

src/Modules/States/HornyState.ts
In current version, horny state caused by time-limited magic does not end when it's duration is finished and just continue indefinitely. It seems the problem is missing `super.Tick()` call in `HornyState`'s overriden `Tick()` method, which I've fixed in this PR.
=> Fix HornyState not ending on timer

lscgLoader-dev.user.js, lscgLoader.user.js, package.json, src/Modules/hypno.ts, src/Modules/injector.ts, src/Modules/item-use.ts, src/Settings/Remote/suggestions.ts
* Fix some hardcoded pronouns in action strings
* Add the ability to make any item have "tamper-proof" reactions. (note: does not immediately make something inescapable, just adds punishments to struggling, using struggle activity, or getting struggle help from someone)
* Item must contain "tamperproof", "tamper-proof" or "tamper proof" in its crafted name or description
* Tamper protection type can then be added in crafted name/description. eg: "electric", "subduing", "self tightening"
* Add checkbox to configure a strip suggestion instruction to pick a random piece of clothing each time (fixes #560)
=> Updates from Dev

src/Modules/activities.ts, src/Modules/core.ts
Xref [BondageProjects/Bondage-College#5278](https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/5278)
Above-mentioned PR overhauls the UI of a number of dialog menu modes (including the `items` mode) for R111, which would render the LSCG share-craft button stuck and unclickable behind the new subscreen's bew DOM elements. This issue is fixed herein by also converting the relevant LSCG button into a DOM element and hooking into the new API.
Includes changes both suitable for the beta-period and full R111 release.
Marking as draft for now until the upstream PR has been merged.
Examples
---------
https://github.com/user-attachments/assets/c733af77-ef74-464d-ba7c-7471594e8f60
=> MAINT: Adapt the share-craft-button to the R111 dialog mode rework

src/Modules/item-use.ts
This fix issue #594
For some reason, the game code don't like when changing the difficulty in item.Property.Difficulty, it always seems to trigger the function ValidationSanitizeProperties() from the base game code. Even when trying to set this property with function like ExtendedItemSetProperty() the result is the same.
On the other hand, only setting item.Difficulty seem to works fine, i don't think the other one is being used for the difficulty calculation, even when it exist.
Note also: this bug not only remove locks, but it seem to also reset some options on an ExtendedItem.
=> Fix for selftightening item that remove locks (issue #594)

src/Modules/core.ts, src/Modules/item-use.ts, src/club_existing/bc/Typedef.d.ts
Small follow up on https://github.com/littlesera/LSCG/pull/596 with a change I had forgotten to take into account:
The `ItemActivity` object now has a new `Group` parameter (representing the target group of the activity), a group which, as of this PR, is now properly passed along in the `ManualGenerateItemActivitiesForNecklaceActivity()`.
=> BETA: Ensure that the group name is passed along when constructing `ItemActivity` objects

src/Modules/States/BarrierState.ts, src/Modules/item-use.ts, src/Modules/magic.ts, src/Modules/states.ts, src/Settings/Models/magic.ts, src/Settings/magic.ts, src/club_existing/type-overrides.d.ts
**New Magic barrier spell effect:**
- Add +5 defense against incoming spell
- If saved against incoming spell the barrier will send the spell back to the sender !
- If not saved, the Player will still suffer from the incoming spell
- The magic barrier is one time use only, whether the player has saved against the spell or not, the magic barrier will disapear after.
**New Disarm spell effect:**
- remove the hand held item fo the target
**New Voice casting ability:**
- Ability to cast spell by sending normal message in chat: `<SpellName> <TargetName>`
- Limited to only one target
- Wand not requiered
If any change are required, let me know!
Azer #172401
=> New Magic features: Magic barrier and Voice casting

src/Modules/chaotic-item.ts, src/Settings/Models/settings.ts, src/Settings/global.ts, src/Settings/setting_definitions.ts, src/main.ts
**New feature: Chaotic and Evolving restraints**
- Simply add the specific keyword in the crafted item's name or description Keyword for Chaotic item's: chaotic, living, sentient, changing Keyword for Evolving item's: evolving, evolve, spreading, spread
- Chaotic restraints will change the item's options randomly every 5min
- Evolving restraints will slowly evolve to the last of the item's option (usually the last option is the most restrictive)
- This feature also change some additional option such as checkbox or voice trigger (on the modular belt for example)
- Possibility to disable it in LSCG's General settings
_In simple word Chaotic restraint can be made similarly to tamperproof item, and will just change all item's options randomly (except for evolving variant that will increase …
=> New feature: Chaotic and Evolving restraints

src/Modules/chaotic-item.ts, src/Settings/global.ts
Chaotic items: Added ability to add 'quick' and 'slow' keyword to reduce or increase the trigger time. (New trigger time: default=10min quick=3min slow=30min)
- New default time: 10min
- Quick keywords reduce the trigger time to 3min
- Quick keywords: "quick", "quickly", "rapidly", "fast"
- Slow keywords increase the trigger time to 30min
- Slow keywords: "slow", "slowly"
=> Chaotic items: Added ability to add 'quick' and 'slow' keyword

src/Modules/chaotic-item.ts
Logic bugs:
- Fixed some numeric properties not evolving from 0 value due to treating it as a boolean;
- Fixed vibrator settings not evolving while spewing console warnings.
Refactoring:
- Extracted property mutation logic to a separate class for readability;
- Changed various small parts of code to be more concise;
- Fixed a few typos.
=> Chaotic items refactoring and small fixes

src/Modules/chaotic-item.ts, src/regEscape.ts, src/utils.ts
This PR, serving a bit is a proof of concept, changes a couple of thing related to how LSCG chaotic- and evolving-keywords are presented towards the user:
* Rather then retaining their square brackets, the brackets are now removed and the relevant term is italicized in button labels/tooltips, blending more seamlessly into the rest of the tooltips (square brackets tend to stand out a lot and have a questionable visual appeal) while stile signifying some importance of the respective term. Note that this only affects how things are rendered _after_ equipping the item; the actual crafting config remains and data storage model remain untouched.
* The chaotic- and evolving-keywords are now explicitly added to the "Status & Effects` section of the tooltip. While currently still lacking, there is …
=> ENH: Improve the item UI related to chaotic- & evolving-keywords

lscgLoader-dev.user.js, lscgLoader.user.js, package.json, src/Modules/core.ts, src/Modules/magic.ts
* Integrate change from @bananarama92 to better display bracketed keywords in crafted item names and descriptions
=> Bracketed keyword display fix

src/Modules/chaotic-item.ts
Minor follow up on https://github.com/littlesera/LSCG/pull/630: makes a number of UI-related keyword detection loops capitalization agnostic.
=> BUG: Make the chaotic/evolving UI modifications capitalization independent

src/Modules/magic.ts
Closes https://github.com/littlesera/LSCG/issues/636
Fixes the issue below by unloading the relevant dialog screen before opening the spell menu.
Examples
----------
=> BUG: Fix the spell menu failing to properly exit the dialog subscreen

src/Modules/item-use.ts, src/Modules/magic.ts
Previously you could still steal an item while fully tied up, which could get a little bit silly.
=> BUG: Ensure that the `Steal` activity requires ones hands to be untied

src/Modules/opacity.ts
Ever since R115 the [`ElementValue()`](https://gitgud.io/BondageProjects/Bondage-College/-/blob/607b4bf1852e171c909390c1cb0eae11e654fb3f/BondageClub/Scripts/Element.js#L3-22) function dispatches an `input` event whenever using it to set a value. This runs into a problem with a few LSCG functions, namely those with input event listeners that use `ElementValue()` to further modify their own input values, thus triggering nasty infinite recursion loops.
=> BUG: Fix opacity element changes triggering an infinite recursive loop

src/Modules/item-use.ts
Closes https://github.com/littlesera/LSCG/issues/678
Fixes a description decode operation which I originally missed back in https://github.com/littlesera/LSCG/pull/574.
=> BUG: Fix the LSCG display craft feature failing to decode extended craft descriptions

src/Modules/chaotic-item.ts
Fix that chaotic item was triggering for only one item instead of all.
Due to most likely typo in the code (code change self explanatory).
Fix issue #702
=> Fix chaotic item trigger only one item

src/Modules/activities.ts
Fixes people able to use the `Grab` action (_e.g._ grabbing someones tail) while their hands were tied. I'd argue this is a bug at least, the whole "grabbing things while you can't use your hands" thing.
=> BUG: Ensure that the `Grab` action requires ones hands to be untied
