src/Modules/hypno.ts

Add chat filtering based on if name is spoken or if triggering member is speaking

hypno update to main

---

package.json
src/Modules/commands.ts
src/Modules/item-use.ts

- Add /lscg 'roll', 'roll-attack', and 'roll-defend' commands
- Fix bug where edging will subtract entire arousal progress from roll modifier.

Roll command

---

src/Modules/activities.ts
src/Modules/injector.ts
src/Modules/item-use.ts
src/Modules/lipstick.ts

Add more items

---

src/Settings/Models/settings.ts
src/Settings/Remote/hypno.ts

Addresses #71 
Note: Requires "requires hypnotizer" to be false as drugs do not track a "speaker"

allow trance access when drugged, if 'require hypnotizer' is false

---

lscgLoader.user.js
package.json
src/Modules/core.ts
src/Modules/injector.ts
src/Settings/Models/settings.ts
src/Settings/Remote/mainmenu.ts
src/Settings/injector.ts
src/Settings/mainmenu.ts
src/utils.ts

Injector Text Fix + Update Beep

---

src/Modules/item-use.ts

BC ball gag mouth item and necklace have inverse color order. This fix is to manually handle that when transferring between the two.
note: hand ballgag has just a single color, so when implementing hand to/from neck, need to also make sure it's manually handled.

Add check for color switching. specifically for ballgags

---

src/Modules/activities.ts
src/Modules/item-use.ts

- Implement hand <-> necklace automation
- Fix penis and dildo interference. Allow penis to piggy back on standard "RubItem" activity, and add custom "SlapWith"

Hand <-> necklace

---

src/Modules/activities.ts
src/Modules/item-use.ts

- fix bandana <-> scarf name mismatch
- fix item unavailable blocking when custom gagging

Permission and Naming fixes

---

src/Modules/activities.ts
src/Modules/commands.ts
src/Modules/core.ts
src/club_existing/type-overrides.d.ts
src/utils.ts

establish arm-grab and build escape attempt mechanic

---

src/Modules/collar.ts
src/Modules/core.ts
src/Modules/hypno.ts
src/Modules/remoteUI.ts
src/Settings/Models/collar.ts
src/Settings/Models/injector.ts
src/Settings/Models/settings.ts
src/Settings/Remote/collar.ts
src/Settings/Remote/hypno.ts
src/Settings/Remote/mainmenu.ts
src/Settings/collar.ts
src/Settings/global.ts
src/Settings/hypno.ts
src/Settings/injector.ts
src/Settings/mainmenu.ts
src/Settings/reset.ts
src/Settings/settingBase.ts
src/Settings/settingUtils.ts

- Added as 'purchasable' collar, inspired from and "sold by" Andrew
- See wiki for updated documentation around this
- Restructure settings to support multi-pages
- Move hand choke and suffocation to first page of new "Breathplay" section
- Collar settings on second page of "Breathplay"
- Move chloroform settings to second page of "Drug Enhancements"

Breathplay Control Collar

---

package.json
src/Modules/activities.ts
src/Modules/collar.ts
src/Modules/injector.ts
src/Modules/item-use.ts
src/Modules/remoteUI.ts

- Biggest change is refactor grab leashing internals.

Various fixes

---

src/Modules/commands.ts
src/Settings/Models/collar.ts
src/Settings/Models/settings.ts
src/Settings/Remote/collar.ts
src/Settings/Remote/mainmenu.ts
src/Settings/collar.ts
src/Settings/mainmenu.ts
src/Settings/settingBase.ts

- add immersive to collar settings
- rename command to 'show-triggers'
- reveal hypno and collar triggers if not set immersive.
- allow self-tighten and self-loosen via command if unrestrained.
- '/lscg collar [tight/loose]
resolved #117

Command additions

---

src/Modules/collar.ts
src/Modules/commands.ts
src/Settings/Models/collar.ts
src/Settings/Models/settings.ts
src/Settings/Remote/collar.ts
src/Settings/collar.ts
src/utils.ts

- Let whispers activate collar triggers
- Add "/lscg collar [tight/loose/stats]" commands that publically manipulate the collar if allowed
- Allow collar module to be be active on any collar
- Allow collar module to work on crafted collars if the base matches the configured base type

Collar Updates

---

src/Modules/core.ts
src/Settings/Remote/collar.ts
src/Settings/Remote/remoteBase.ts
src/Settings/collar.ts

Simply use non-exit clicks to flip dirty flag.

Try to only send remote packet if something changed. 

---

src/Modules/hypno.ts

- If immersive, always blank out triggers
Resolves #140 and #138

- Fix name matching for hypno-speech-block.

---

src/Modules/item-use.ts

drop 'large' or 'small' craft properties when taking gag from mouth.

---

src/Modules/injector.ts

fix "activated mask add" emote on disabled mask add

---

src/Modules/core.ts

add sync packet to core load if already in a chat room

---

src/Modules/injector.ts

significant reduce continuous delivery chatter

---

src/Modules/activities.ts

fix mis-check on incoming grab

---

src/Modules/lipstick.ts
src/Settings/Models/base.ts
src/Settings/Models/settings.ts
src/Settings/global.ts

add dry lipstick setting to public packet

---

src/Modules/activities.ts
src/Modules/collar.ts
src/Modules/item-use.ts

refactor hand choke into activities as escapable grab

---

package.json
src/Modules/activities.ts
src/Modules/injector.ts

* Grab Horn
* Nuzzle
* Bap
* Headbutt
* Nibble Wings
* Nibble Halo
https://github.com/littlesera/LSCG/discussions/162

Activity adds

---

src/Modules/activities.ts

fix prereq for nibble halo and grab horn

---

src/Modules/hypno.ts
src/Modules/injector.ts

Prevent self awakening

---

src/Settings/mainmenu.ts

Fix invisible buttons on menu when restrained

---

src/Modules/hypno.ts
src/Settings/Models/hypno.ts

Fix hypno trigger cycle

---

src/Modules/hypno.ts
src/Settings/Models/hypno.ts
src/Settings/hypno.ts

Allow configuration of hypnotized eye type + color 

---

src/Modules/activities.ts
src/Modules/collar.ts
src/Modules/commands.ts
src/Modules/core.ts
src/Settings/Models/collar.ts
src/Settings/Models/settings.ts
src/Settings/Remote/collar.ts
src/Settings/collar.ts
src/club_existing/type-overrides.d.ts
src/utils.ts

Add collar buttons setting + activities

---

src/Modules/activities.ts
src/Modules/collar.ts
src/Modules/injector.ts
src/Settings/Models/collar.ts
src/Settings/Models/settings.ts
src/Settings/collar.ts

Force sleep (like drugged) for 2 minutes after breathplay passout.

---

src/Modules/injector.ts

Allow vr headset set to trance background to induce hypnosis

---

src/MiniGames/Sleepy.ts
src/club_existing/bc/Scripts/Skill.d.ts

fix null ref on minigame victory

---

src/Modules/States/HypnoState.ts
src/Settings/hypno.ts

Hypno eye fixes

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/States/PolymorphedState.ts
src/Modules/States/RedressedState.ts
src/Modules/magic.ts
src/Settings/Models/magic.ts
src/Settings/magic.ts
src/main.ts
src/utils.ts

This is a one-way change. You will loose data if you somehow go back to an old version of LSCG.

Compression changes

---

rollup.config.mjs
src/Modules/States/PolymorphedState.ts
src/Modules/States/RedressedState.ts

copy the full properties of the item over.

Fix layering issue with outfit/polymorph

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/States/ResizedState.ts
src/Modules/core.ts
src/Modules/injector.ts
src/Modules/magic.ts
src/utils.ts

- Update to 0.3.14
- Fix quaff on others
- Honor Player.VisualSettings.ForceFullHeight
- Fix room block for magic (Fantasy Items)
- Add small protection to incoming remote access changes to isolate to only enabled sections
- Fix spell duration message if spells are not limited
- Don't resist beneficial drinks
- Add paralysis to IsIncapacitated list (used for immersive settings block)
- Fix hypno headset wtill working if drug hypno is disabled

Fixes and updates to 0.3.14

---

src/Modules/States/ResizedState.ts

use more appropriate hook location to adjust height ratios

---

lscgLoader-dev.user.js
lscgLoader.user.js
package-lock.json
package.json
src/Modules/States/PolymorphedState.ts
src/Modules/States/RedressedState.ts
src/Modules/States/ResizedState.ts
src/Modules/commands.ts
src/Modules/core.ts
src/Modules/magic.ts
src/Settings/Models/magic.ts
src/Settings/Models/settings.ts
src/Settings/Remote/magic.ts
src/Settings/magic.ts
src/club_existing/type-overrides.d.ts
src/main.ts
src/modules.ts
src/utils.ts

* Fix height flickering on reduce/enlarge
* Expose drug/netgun/spell keywords for MBS
* Fix spell buttons when using beta room customization
* Add commands to get/parse trimmed down outfit/polymorph codes straight to and from clipboard
* /lscg get-outfit-code
* /lscg get-polymorph-code
* /lscg parse-code

Magic fixes and updates

---

src/Modules/misc.ts

Add timer check for chloro to support wheel applied rags.

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/States/PolymorphedState.ts
src/Modules/States/ResizedState.ts
src/Modules/magic.ts
src/Modules/misc.ts
src/Settings/Models/magic.ts
src/Settings/Models/settings.ts
src/Settings/Remote/magic.ts
src/Settings/magic.ts
src/utils.ts

* Add config to allow players to prevent genital/pronoun changes to themselves from polymorph effects
* Fix chloro not detecting it's addition from things like MBS wheel

Polymorph and Chloro fixes

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/States/PolymorphedState.ts
src/Modules/States/RedressedState.ts
src/Modules/activities.ts
src/Modules/item-use.ts
src/Modules/magic.ts
src/Settings/Models/magic.ts
src/Settings/Models/settings.ts
src/Settings/magic.ts

* Version bump to v0.3.19
* Add whitelist-only magic setting
* Add fellatio activities
* Add legs+feet nuzzling
* Add breb eating
* Fix #335 
* Fix 'ride with--' activitity still allowed when clothed

Merge Changes from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/magic.ts

Fix issue of magic whitelist requirement preventing casting on yourself.

Magic Whitelist hotfix

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/States/ResizedState.ts
src/Modules/magic.ts
src/Settings/Models/magic.ts
src/Settings/magic.ts

* Remove "Reduce" Spell effect from LSCG Magic due to feature abuse

Remove Reduce Spell Effect

---

src/Modules/activities.ts
src/Modules/collar.ts
src/Modules/hypno.ts
src/Modules/injector.ts
src/Modules/item-use.ts
src/Modules/magic.ts

Change all pronouns where it could be easilly replaced with `replace_template`.
Changed some pronounces in custom activities that related to Player.
Not sure tho about pronouns related to other character. 
So here need some help on that.

Change pronounces to be gender-dependant

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/Migrators/BaseMigrator.ts
src/Modules/Migrators/StateMigrator.ts
src/Modules/States/HypnoState.ts
src/Modules/commands.ts
src/Modules/core.ts
src/Modules/hypno.ts
src/Modules/item-use.ts
src/Settings/mainmenu.ts
src/main.ts
src/utils.ts

* Data storage change back to Base64 to save space
* Experimental sparse matrix clean function built and makes reports to console on save, but not integrated into the actual save yet for safety.
* Export/Import buttons added to main menu
* Includes _all_ settings except for stats, so be wary when importing. Mostly useful as settings backup.
* Allow any handheld item to be used to boop a nose

Updated from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/boops.ts
src/Modules/core.ts

* Fix item boop reactions
* Add 'Crafted By' tooltip for shared crafts from others

Fixes from Dev

---

src/Modules/States/HypnoState.ts
src/Settings/hypno.ts

* Fixes 14th eyes type not being selectable and colorable

New eyes type fixes

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json

Hypno Eye update from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/item-use.ts
src/Modules/magic.ts

* Fix item use rope ties
* Fix grammer in potion quaff on self

Hotfixes from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/States/XRayVisionState.ts
src/Modules/core.ts
src/Modules/opacity.ts
src/Settings/Models/base.ts
src/Settings/Models/settings.ts
src/Settings/Remote/magic.ts
src/Settings/global.ts
src/Settings/magic.ts
src/Settings/mainmenu.ts
src/club_existing/bc/Typedef.d.ts
src/club_existing/type-overrides.d.ts
src/utils.ts

* Fix LSCG beep communication outside friends list
* Add ability to block xray vision per-clothing item
* Add ability to modify opacity on others
* Add global setting to block this

Updates and Fixes

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/opacity.ts
src/main.ts

* Fix asset hide/alpha layers restoration on opacity removal (+xray cure)

Hotfix from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/magic.ts
src/Settings/Models/settings.ts
src/Settings/Remote/magic.ts
src/Settings/magic.ts
src/club_existing/bc/Scripts/Server.d.ts
src/club_existing/bc/Typedef.d.ts
src/club_existing/type-overrides.d.ts
src/main.ts
src/utils.ts

* Change xray vision on you to be strictly opt-in in alignment with general mod philosophy
* Switch mod data storage to Player.ExtensionSettings in accordance with current best practice

Updates from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/activities.ts
src/main.ts

* Fix DrawImageResize argument change bug
* Wrap version string parse on load in try/catch

Beta Fixes from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/hypno.ts
src/Modules/injector.ts
src/Modules/states.ts
src/club_existing/bc/Screens/Online/ChatRoom/ChatRoom.d.ts
src/club_existing/bc/Screens/Online/ChatRoom/ChatRoomMap.d.ts

* Clean up deprecated functions and variables

R102 fixes from Dev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/injector.ts

* Update respirator check to inspect all mouth slots

Respirator mouth slot fix

---

src/Modules/core.ts

Xref https://gitgud.io/BondageProjects/Bondage-College/-/merge_requests/4900
Adapts to the R103 optimizations of crafted item handling in `DialogInventoryBuild`, the additional asset parameter added to `DialogCanUseCraftedItem` being of particular importance here.
Marking as draft for the time being until aforementioned upstream PR is merged.

MAINT:  Adapt to the R103 `DialogInventoryBuild` changes

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/hypno.ts

Move logic into ChatMessageHandler run between sensory dep and chat message render
Fixes #495

Refactor away from "SpeechGarble" hook 

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/hypno.ts
src/Settings/Models/hypno.ts
src/Settings/Models/settings.ts
src/Settings/Remote/hypno.ts
src/Settings/hypno.ts

* Fix Blocked Instructions
* Add "Always submit" options
* Remove dominance rating modifier

Hypno Suggestion fixes

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/leashing.ts

* Simplify custom leashing room joins and support cross-space if allowed

Custom Leashing Across Spaces

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/activities.ts
src/Modules/collar.ts
src/Modules/commands.ts
src/Modules/core.ts
src/Modules/hypno.ts
src/Modules/leashing.ts
src/Modules/misc.ts
src/utils.ts

Fix escaping local text when not intented

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/item-use.ts

* Allow breath control collars to activate if "tamperproof" and "self-tightening"

Hook up breath control with tamper proof detection

---

lscgLoader-dev.user.js
lscgLoader.user.js
package.json
src/Modules/core.ts
src/Modules/item-use.ts
src/Modules/opacity.ts
src/club_existing/type-overrides.d.ts
src/utils.ts

* Fix multi-layer opacity
* Add ability to share crafted item details with chat without applying it to someone

Updates and Fixes fromDev

---

lscgLoader-dev.user.js
lscgLoader.user.js
package-lock.json
package.json
src/Modules/hypno.ts
src/utils.ts

* Allow BCX "Listen to my Voice" rule to activate hypno triggers/awakeners/suggestions
* only blank out hypno triggers if they are 'active'

Hypno Updates

---

lscgLoader-dev.user.js
lscgLoader.user.js
package-lock.json
package.json
src/Modules/States/XRayVisionState.ts
src/Modules/magic.ts
src/Modules/opacity.ts
src/Settings/Models/magic.ts
src/Settings/Models/settings.ts
src/Settings/Remote/magic.ts
src/Settings/magic.ts

* Make lscg and vanilla opacity to work together
* Allow setting blocked spell effects to be allowed when cast on yourself

Opacity and Spell Updates

---

src/Modules/States/BarrierState.ts
src/Modules/item-use.ts
src/Modules/magic.ts
src/Modules/states.ts
src/Settings/Models/magic.ts
src/Settings/magic.ts
src/club_existing/type-overrides.d.ts

* Barrier spell effect
* Disarm spell effect
* Voice casting with customizable phrase override

Update and merge spell changes from Azer into dev

---

src/Modules/magic.ts

- **Fix:** voice casting was ignoring the target's interact permission and blacklist
- **Change:** Allow voice casting when stuttering _(only for simple stuttering, voice casting will still not work with heavy stuttering or other talk effects)_

Fix for voice casting

---

lscgLoader-dev.user.js
lscgLoader.user.js
package-lock.json
package.json
src/Modules/splatter.ts

* Fix 'rub with towel' not cleaning nipple splatters

Nip splat clean fix

---

src/Modules/States/SpreadingOutfitState.ts
src/Modules/core.ts
src/Modules/spreading-outfit.ts
src/Modules/states.ts
src/Settings/Models/settings.ts
src/Settings/Models/spreading-outfit.ts
src/Settings/Remote/mainmenu.ts
src/Settings/Remote/spreading-outfit.ts
src/Settings/setting_definitions.ts
src/Settings/spreading-outfit.ts
src/club_existing/type-overrides.d.ts
src/main.ts

New feature: Spreading outfit module
The recipient can choose to fight against it.. but it'll not stop until the outfit spread fully~
- Equip/bind progressively the outfit code associated
- Can be setup & started remotely (using lscg remote settings)
- Repeatable, for a long term cursed outfit~
- Everything configurable
- The outfit will not be removed by itself~
Hi, sorry to bother you, but i came up with a new thing... again~
I hope you will like it, and let me know if i need to make any adjustement!
Thank you for your amazing work and sorry in advance to put some extra work on you.

New feature: Spreading outfit module
